#!/usr/bin/python
"""Simple utility that converts tic54x binary output to hex readable by gcc.
-- wumpus <blacksphere@goliath.darktech.org> 2003

Usage: %s <infile>.bin <outfile>.hex
"""

import sys

if len(sys.argv)<3:
	print __doc__ % (sys.argv[0],)
	sys.exit(1)

infile = sys.argv[1]
outfile = sys.argv[2]

# read infile
ifd = open(infile, "rb")
data = ifd.read()
ifd.close()
if len(data) & 1:
	print "File smells bad. (number of bytes must be even)"
	sys.exit(1)
ofd = open(outfile, "w")

x = 0
size = len(data)
ofd.write("/* Autogenerated by halfwordify.py -- Do not manually modify this file! */\n")
ofd.write("{\n")
while x < size:
    str = ""
    sub = 0
    while sub < 8 and x < size:
        str += "0x%02X%02X," % (ord(data[x+1]),ord(data[x+0]))
        sub += 1
        x += 2
    if x == size:
        str = str[0:-1]
    ofd.write(str)
    ofd.write("\n")
ofd.write("}\n")
