export COMPILER_PATH=/home/-gamez-/gccarm/arm-thumb-elf/bin/
CC = /home/-gamez-/gccarm/arm-thumb-elf/bin/gcc
GAS = /home/-gamez-/gccarm/arm-thumb-elf/bin/as -EB
OBJDUMP = /home/-gamez-/gccarm/arm-thumb-elf/bin/objdump
OBJCOPY = /home/-gamez-/gccarm/arm-thumb-elf/bin/objcopy
AR = /home/-gamez-/gccarm/arm-thumb-elf/bin/ar
